[[redirects]]
 from = "https://commande.kinosa.fr/*"
 to = "https://m.me/KinosaCommande?ref=bd8f0800-2377-11eb-b932-a3b19102b7bc"
 status = 200
 force = true
 
 [[redirects]]
 from = "https://draaf-fam.kinosa.fr/*"
 to = "https://www.leatsy.fr/guest/kinosa"
 status = 200
 force = true

 [[redirects]]
 from = "https://draaf.fam.kinosa.fr/*"
 to = "https://www.leatsy.fr/guest/kinosa"
 status = 200
 force = true

 [[redirects]]
 from = "https://flyer.kinosa.fr/*"
 to = "https://m.me/KinosaCommande?ref=931948c0-236c-11eb-b932-a3b19102b7bc"
 status = 200
 force = true
